[project]
name = "langflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langflow",
]

[tool.uv.sources]
langflow = { workspace = true }
